queue

diff --git a/queue-mgmt/qrun b/queue-mgmt/qrun
--- a/queue-mgmt/qrun
+++ b/queue-mgmt/qrun
@@ -8,6 +8,8 @@ OPTIONS:
   -d, --queue-dir
   -n, --suppress-output"
 
+# TODO add --fork option to preserve logs and exit code
+
 . qadd-common
 
 qcleanup
@@ -60,7 +62,6 @@ fi
 pwd=`cat "$queue_dir/$next_item_id.pwd"`
 umask=`cat "$queue_dir/$next_item_id.umask"`
 
-readlink /proc/self/ns/pid > "$queue_dir/$next_item_id.pidns"
 declare -a command=()
 exec {fd}<"$queue_dir/$next_item_id.comm"
 while read -r -d $'\0' -u $fd arg
@@ -71,6 +72,7 @@ exec {fd}>&-
 
 # task's PID is gonna be ours at the end
 echo $$ > "$queue_dir/$next_item_id.pid"
+readlink /proc/self/ns/pid > "$queue_dir/$next_item_id.pidns"
 if [ ! $very_quiet ]
 then
 	echo "qrun: starting task $next_item_id, pid: $$, command: ${command[*]}" >&2
@@ -91,4 +93,5 @@ set -e
 . "$queue_dir/$next_item_id.func.bash"
 cd "$pwd"
 umask "$umask"
-exec "${command[@]}"
+exec -- "${command[@]}"
+exit 127
