new fuse mount type helper

diff --git a/user-tools/override/mount b/user-tools/override/mount
--- a/user-tools/override/mount
+++ b/user-tools/override/mount
@@ -25,7 +25,7 @@ then
 	then
 		exit 0
 	else
-		echo "trying system fstab" >&2
+		echo "mount: error occured while using ~/.fstab; trying system fstab..." >&2
 	fi
 fi
 
